language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

env:
  - DB=mysql
  - DB=sqlite


branches:
  except:
    - ModelToRecordMapping

matrix:
  include:
    - name: '[mysql] 5.5 / [PHP] 7.2'
      os: linux
      dist: precise
      php: '7.2'
      env: DB=mysql #mysql 5.5
      services:
        - mysql
    - name: '[mysql] 5.6 / [PHP] 7.2'
      os: linux
      dist: trusty
      php: '7.2'
      env: DB=mysql #mysql 5.6
      services:
        - mysql
    - name: '[mysql] 5.7 / [PHP] 7.2'
      os: linux
      dist: xenial
      php: '7.2'
      env: DB=mysql #mysql 5.7
      services:
        - mysql
    - name: '[mariadb] 10.0 / [PHP] 7.2'
      env: DB=mariadb
      php: '7.2'
      addons:
        mariadb: '10.0'
      services:
        - mysql
    - name: '[mariadb] 10.1 / [PHP] 7.2'
      env: DB=mariadb
      php: '7.2'
      addons:
        mariadb: '10.1'
      services:
        - mariadb
    - name: '[mariadb] 10.2 / [PHP] 7.2'
      env: DB=mariadb
      php: '7.2'
      addons:
        mariadb: '10.2'
      services:
        - mariadb
    - name: '[mariadb] 10.3 / [PHP] 7.2'
      env: DB=mariadb
      php: '7.2'
      addons:
        mariadb: '10.3'
      services:
        - mariadb
    - name: '[mariadb] 10.4 / [PHP] 7.2'
      env: DB=mariadb
      php: '7.2'
      addons:
        mariadb: '10.4'
      services:
        - mariadb

  allow_failures:
    - php: nightly

sudo: false

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - cp phpunit_db_config.travis.$DB.php phpunit_db_config.php;

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'create database dive;'; fi
  - if [[ "$DB" == "mariadb" ]]; then mysql -e 'create database dive;'; fi

script:
  - vendor/bin/phpunit
