language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

branches:
  except:
    - ModelToRecordMapping

matrix:
  include:
    - name: 'mysql5.5'
      os: linux
      dist: precise
      env: DB=mysql #mysql 5.5
    - name: 'mysql5.6'
      os: linux
      dist: trusty
      env: DB=mysql #mysql 5.6
    - name: 'mysql5.7'
      os: linux
      dist: xenial
      env: DB=mysql #mysql 5.7
    - name: 'sqlite'
      env: DB=sqlite
    - name: 'mariadb10.0'
      env: DB=mariadb
      addons:
        mariadb: '10.0'
    - name: 'mariadb10.1'
      env: DB=mariadb
        addons:
          mariadb: '10.1'
  - name: 'mariadb10.2'
    env: DB=mariadb
      addons:
        mariadb: '10.2'
  - name: 'mariadb10.3'
    env: DB=mariadb
    addons:
      mariadb: '10.3'
  - name: 'mariadb10.4'
    env: DB=mariadb
      addons:
        mariadb: '10.4'

  allow_failures:
    - php: '7.3'
    - php: nightly

sudo: false

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - cp phpunit_db_config.travis.$DB.php phpunit_db_config.php;

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'create database dive;'; fi

script:
  - vendor/bin/phpunit
