language: php
php:
  - hhvm-nightly
  - hhvm
  - nightly
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.3.3

before_script:
  - composer self-update
  - composer install
  - mysql -e 'create database dive;'
  - cp phpunit_db_config.travis.php phpunit_db_config.php
