language: php
php:
  - hhvm-nightly
  - hhvm
  - nightly
  - 5.6
  - 5.5
  - 5.5.9
  - 5.4
  - 5.3
  - 5.3.3
  
matrix:
  allow_failures:
    - php: nightly
    - php: 5.5 
      env: DB=sqlite
    - php: 5.6 
      env: DB=sqlite
    
env:
 - DB=mysql
 - DB=sqlite

#sudo: required
#
#before_install:
#  - sudo apt-get update
#  - sudo apt-get install sqlite3 (alternative version?)

install:
  - composer self-update
  - composer install
  - cp phpunit_db_config.travis.$DB.php phpunit_db_config.php;

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'create database dive;'; fi
