language: php
php:
  - hhvm-nightly
  - hhvm
  - nightly
  - 5.6
  - 5.5
  - 5.5.9
  - 5.4
  - 5.3
  - 5.3.3

matrix:
  allow_failures:
    - php: nightly
      env: DB=mysql # not failing, but phpunit currently returns with exit code 139
    - php: hhvm-nightly # currently not supported by travis (no nightly bilds on precise)

env:
 - DB=mysql
 - DB=sqlite

sudo: false
#sudo: required
#
#before_install:
#  - sudo apt-get update
#  - sudo apt-get install sqlite3 (alternative version?)

install:
  - composer self-update
  - composer install
  - cp phpunit_db_config.travis.$DB.php phpunit_db_config.php;

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'create database dive;'; fi
