language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

branches:
  except:
    - ModelToRecordMapping

matrix:
  allow_failures:
    - php: '7.3'
    - php: nightly

env:
  - DB=mysql
  - DB=sqlite

sudo: false

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - cp phpunit_db_config.travis.$DB.php phpunit_db_config.php;

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'create database dive;'; fi

script:
  - vendor/bin/phpunit
