language: php
php:
  - nightly
  - '7.0'
  - '7.1'
  - '7.2'
  - '5.6'
  - '5.5'

branches:
  except:
    - ModelToRecordMapping

matrix:
  allow_failures:
    - php: 5.5
      env: DB=sqlite # sqlite below 3.8.10.2 has a bug
    - php: 5.6
      env: DB=sqlite # sqlite below 3.8.10.2 has a bug
    - php: 7.2
    - php: nightly

env:
 - DB=mysql
 - DB=sqlite

#sudo: false
sudo: required
#
before_install:
  - sudo apt-get update
#  - sudo apt-get install sqlite3 (alternative version?)

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - cp phpunit_db_config.travis.$DB.php phpunit_db_config.php;

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'create database dive;'; fi

script:
  - vendor/bin/phpunit
