language: php
php:
  - hhvm-nightly
  - hhvm
  - nightly
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.3.3

env:
 - DB=mysql
 - DB=sqlite

#sudo: required
#
#before_install:
#  - sudo apt-get update
#  - sudo apt-get install sqlite3 (alternative version?)

install:
  - composer self-update
  - composer install
  - cp phpunit_db_config.travis.$DB.php phpunit_db_config.php;

before_script:
  - if [[ "$DB" == "sqlite" ]]; then sqlite3 -version; fi
  - if [[ "$DB" == "mysql" ]]; then mysql --version; mysql -e 'create database dive;'; fi
