language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3.3
  - 5.3
  - hhvm

before_script:
  - composer self-update
  - composer install
  - mysql -e 'create database dive;'
  - cp phpunit_db_config.travis.php phpunit_db_config.php
